### ISSUE TITLE
How do I specify the format?

### ISSUE THREAD

**Issue by salmiakki** [dannyfritz/atom-date#10]
How do I specify the format? It would be nice to have this info in the readme as well.

**Comment by dannyfritz** [comment]
If you go to the package's settings there are fields for specifying the format.

![atom_2016-05-27_08-49-48](https://cloud.githubusercontent.com/assets/315788/15611542/f9dca2e8-23e7-11e6-9f71-1fbab4c02bdb.png)

**Comment by salmiakki** [comment]
Thanks!

**Comment by HostOnNet** [comment]
Thanks, i was trying to find this, it will be great if we have a wiki with these tips for new users.
