### ISSUE TITLE
Allow custom datetime format

### ISSUE THREAD

**Issue by Evpok** [dannyfritz/atom-date#14]
I'd like to be able to specify a datetime format other than `<DATE> <TIME>`, but e.g. `<DATE>T<TIME>` (aka [EDTF](https://www.loc.gov/standards/datetime/pre-submission.html#datetime)).  I guess a separate format field for datetime would do the trick.

**Comment by dannyfritz** [comment]
I'm open to a pull request to add this feature. :)

**Comment by dannyfritz** [comment]
Functionality should be there now in `v1.2.0` https://github.com/dannyfritz/atom-date/commit/a4d59dffb29b62d826af5ccfdd28b6a5e07d5a7b
