### ISSUE TITLE
Add timezone?

### ISSUE THREAD

**Issue by klundberg** [dannyfritz/atom-date#15]
Hi! is it feasible to add timezones as a format option? I'd love to be able to insert a full ISO8601 date string including the timezone into my work.

Thanks!

**Comment by dannyfritz** [comment]
Can you try using `ZZ` in your format?

**Comment by klundberg** [comment]
None of those four worked. I used an explicit version of the default datetime format and appended each one to it, with no luck.

**Comment by dannyfritz** [comment]
I'll take a look at this in the next few weeks. Definitely want it to support timezone formatting.

**Comment by dannyfritz** [comment]
Timezones are supported in the latest version.

Switched to using this library: https://date-fns.org/v1.28.5/docs/format
