### ISSUE TITLE
Custom date format broken after latest update

### ISSUE THREAD

**Issue by dhrivnak** [dannyfritz/atom-date#17]
I have the following custom date format:

```
+------------------+
| YYYY-MM-DD (DDD) |
+------------------+
```

Before I updated to version 2.0.0 this resulted in dates that looked like:

```
+------------------+
| 2017-08-30 (Wed) |
+------------------+
```

After the update, the same formatter spits out:

```
+------------------+| 2017-09-20 (263) |+------------------+
```

**Comment by dannyfritz** [comment]
v2.0.0 is a major semver change and implies breaking changes.

I switched to a different date library. You can see the options in the README: https://github.com/dannyfritz/atom-date#options

**Comment by dhrivnak** [comment]
I double checked your readme in Atom and it should still work for my
format. Perhaps that needs to be updated as well.

**Comment by dannyfritz** [comment]
According to the docs it should be:
`YYYY-MM-DD (ddd)`

**Comment by dannyfritz** [comment]
Oh, I see what you are saying. I'll have to publish a change to the README once I get to my computer.

**Comment by dhrivnak** [comment]
Cool, thanks!
