### ISSUE TITLE
show your defaults in the blank field, please :)

### ISSUE THREAD

**Issue by brentbiglin** [dannyfritz/atom-date#19]

**Comment by dannyfritz** [comment]
It appears to show the defaults for me. Can you describe more of what is happening? Is it possible both of your fields are configured to `""` and it is showing that?

Reopen if you feel this is a bug or I misinterpreted it.

![atom_2017-10-25_11-35-40](https://user-images.githubusercontent.com/315788/32013557-b565a15a-b978-11e7-847f-f09fb0a8af66.png)
