### ISSUE TITLE
Default format for "Date Time Format" not used.

### ISSUE THREAD

**Issue by gahrae** [dannyfritz/atom-date#22]
The settings for "Date Time Format" reads... "If left blank, this will default to Date Format + Time Format". However, it is not and another format is used.

For example, given the following:
   Date Format = [blank] (therefore DD-MM-YYYY)
   Time Format = [blank] (therefore HH:mm)
We expect the Date Time Format to be generated as DD-MM-YYYY HH:mm.
However, it is not. Another format is used.

For example, the following is generated: "2017-12-06T08:43:28.802-07:00"
But, it should be generated as: "06-12-2017 08:43"

The work-around is to explicitly set Date Time Format to "DD-MM-YYYY HH:mm"
(For interest, it is not possible to set Date Format or Time Format to its "default value")

Btw, thanks for creating this package!

**Comment by gahrae** [comment]
Additional info to assist troubleshooting...

$ atom -v
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

$ apm list --installed
Community Packages (1) /Users/gahrae/.atom/packages
└── date@2.0.3

OS: macOS version 10.12.6

**Comment by dannyfritz** [comment]
Thanks for the issue report!
Should be fixed in v2.1.0 https://github.com/dannyfritz/atom-date/releases/tag/v2.1.0
:smile:
