### ISSUE TITLE
Support Internationalization

### ISSUE THREAD

**Issue by fuzihaofzh** [dannyfritz/atom-date#25]
As date-fns supports different languages, I wonder whether it is possible to add this feature to this tool?

**Comment by dannyfritz** [comment]
I'll welcome a PR for this feature. Seems cool. I glanced at the docs to see what would need to happen and it doesn't look too hard: https://date-fns.org/v1.29.0/docs/I18n#supported-languages

**Comment by maplewizard** [comment]
Dear @dannyfritz , I'm very willing to help but I have no experience in atom development. Could it be possible for you to add this feature when you have free time?

**Comment by bkleinen** [comment]
I think this is done and can be closed with PR  #30
