### ISSUE TITLE
Change timezone

### ISSUE THREAD

**Issue by sysadmnjohn** [dannyfritz/atom-date#26]
I need to change the timezone to UTC, however I see no documentation for this.

**Comment by dannyfritz** [comment]
I will investigate this. Have you thought about what the UI solution would look like? Just a box that accepts a timezone offset or string?

**Comment by dannyfritz** [comment]
This is actually not a straightforward thing to do in JavaScript: https://github.com/date-fns/date-fns/issues/489

**Comment by dannyfritz** [comment]
I can do a toggle between local time and UTC.
