### ISSUE TITLE
Improve instruction how to add keymap

### ISSUE THREAD

**Issue by Louis-Cypher** [dannyfritz/atom-date#28]
I tried to add a keybinding for date:time but it doesn't work. My guess is that this is the case since it is rather unclear to what piece of atom it should be related.

I tried:
`'atom-date':
   'ctrl-alt-t': 'date:time'`

as well as:
`'date':
   'ctrl-alt-t': 'date:time'`

Both don't work.

Thanks in advance

**Comment by dannyfritz** [comment]
The commands you are trying to bind are in the [README](https://github.com/dannyfritz/atom-date#usage).

Perhaps you should look at the Atom configuration manual to help you out: https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings

```cson
'atom-text-editor':
  'ctrl-alt-t': 'date:time'
```

**Comment by Louis-Cypher** [comment]
Of course I read the readme. My thinking that things should either be kind of fully explained or you can safe the effort to document them. To my understanding putting what you wrote me (thanks a lot for that) into to the readme would be already enough.

**Comment by mmarras** [comment]
> The commands you are trying to bind are in the [README](https://github.com/dannyfritz/atom-date#usage).
> 
> Perhaps you should look at the Atom configuration manual to help you out: https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-keybindings
> 
> ```coffee
> 'atom-text-editor':
>   'ctrl-alt-t': 'date:time'
> ```

This was more useful than what's in the readme. A line more wouldn't hurt anyone, I suppose.
