### ISSUE TITLE
New line in the Date/Time Format

### ISSUE THREAD

**Issue by mxgrn** [dannyfritz/atom-date#9]
I'd like to be able to define a Format like this:

      HH24:MI\n

... so that it inserts a new line after the time stamp. Currently it escapes "\n" prior to inserting. Any way to achieve that? Thanks!

**Comment by dannyfritz** [comment]
If you modify your Atom `config.cson` file you can put the unescaped `\n` into it and it works as expected. You are correct in that if you set it through the Atom interface it escapes it to `\\n`. I'll look more into this, but this might be an Atom thing.

**Comment by dannyfritz** [comment]
Looks like this is an issue with Atom's `settings-view` package: https://github.com/atom/settings-view/issues/560

**Comment by mxgrn** [comment]
This solution is good enough for me, thanks for the tip!
